// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Anymatch = require("anymatch");

function anymatch(options, matchers) {
  var fn = Anymatch(matchers, undefined, options);
  return function (str) {
    return fn(str);
  };
}

function anymatchIndex(options, matchers) {
  var fn = Anymatch(matchers, undefined, options);
  return function (str) {
    return fn(str, true);
  };
}

exports.anymatch = anymatch;
exports.anymatchIndex = anymatchIndex;
/* anymatch Not a pure module */
